project:
  type: book

lang: de

book:
  title: "Handbuch zur Entwicklung qualitätsvoller Lehr-Lernmaterialien für die Praxis und Forschung"
  author: 
    - name: "Sascha Bernholt"
    - name: "Ilka Parchmann"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - part: part_why/_why.qmd
      chapters: 
        - part_why/_importance.qmd
        - part_why/_orientations.qmd
    - part: part_how/_how.qmd
      chapters: 
        - part_how/_frameworks.qmd
        - part_how/_criteria_general.qmd
        - part_how/_criteria_specific.qmd
    - summary.qmd


bibliography: zotero.bib
csl: apa.csl
citeproc: false

reference-section-title: References

section-bibliographies:
  cleanup-first: true

filters:
  - at: pre-quarto
    path: section-authors
  - at: pre-quarto
    path: section-bibliographies

format:
  html:
    number-sections: true
    number-depth: 2
    theme:
      - cosmo
      - simplex

editor: source

